### ISSUE TITLE
Content disappears when dragged from sidebar to panel

### ISSUE THREAD

**Issue by gjsjohnmurray** [mattbierner/vscode-docs-view#10]
1. With the view in its default place (Explorer sidebar), select a symbol in a file. The doc displays correctly.
2. Drag the view onto the panel. The doc content disappears.
3. Switch to another tab of the panel, then back to "EXPLORER: DOCUMENTATION". The doc content now appears.

This is on 1.50.1 on Windows.

**Comment by mattbierner** [comment]
@gjsjohnmurray Are you still seeing this? I just tested and it seems to work fine for me on MacOS

**Comment by gjsjohnmurray** [comment]
I no longer get the problem on 1.52.1

Closing.
