### ISSUE TITLE
When in Panel, can tab label be improved?

### ISSUE THREAD

**Issue by gjsjohnmurray** [mattbierner/vscode-docs-view#11]
![image](https://user-images.githubusercontent.com/6726799/96113607-51a08380-0edc-11eb-8071-da43a384dad7.png)

Is the mention of Explorer important?

Maybe label can simply be "DOCUMENTATION" (to save tab space), and tip "Documentation For Current Cursor Position".

**Comment by mattbierner** [comment]
Fixed by #19 I believe
