### ISSUE TITLE
Docs view gone after removing from explorer view

### ISSUE THREAD

**Issue by mmmols** [mattbierner/vscode-docs-view#13]
After removing Documentation tab from explorer view, I can no longer get it back. 
Even after an uninstall I cannot get it back. 

Maybe there should be an option within "Views and More Actions..." to get it back in the explorer? (see screenshot).

Or am I just being silly here. What am I missing??

![image](https://user-images.githubusercontent.com/18280977/96242463-c68ac080-0fa3-11eb-85d2-485ab8bb238b.png)

**Comment by mmmols** [comment]
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

and docs view version v0.0.3

**Comment by mattbierner** [comment]
Try running: `View: Reset view locations` command in the command palette to put it back into the explorer

**Comment by mmmols** [comment]
Thanks @mattbierner. I would still argue that this is rather intrusive since it removes my custom view locations I have placed and it would be a great feature to have the possibility to add it in "Views and More Actions".

Thanks for a much appreciated extension.
