### ISSUE TITLE
Panel hangs in loading state

### ISSUE THREAD

**Issue by joshtemple** [mattbierner/vscode-docs-view#14]
After installing the extension, I reloaded VSCode and moved the Panel from the sidebar to the Integrated Terminal section (not totally sure what this is called).

The panel tries to load but never resolves. No logs in the Extensions section.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/8672171/96487897-3fd81c80-120b-11eb-8151-1cc8424b4566.png">

VSCode version:
```
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (6 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0```

**Comment by mattbierner** [comment]
Closing due to no further reports of the issue
