### ISSUE TITLE
show completed typescript type info not the ellipsis

### ISSUE THREAD

**Issue by tjx666** [mattbierner/vscode-docs-view#15]
For Example: 
![Snipaste_2020-10-21_15-11-02](https://user-images.githubusercontent.com/41773861/96685522-ce859e80-13af-11eb-8c1c-f71aca556b16.png)

**Comment by mattbierner** [comment]
This is not caused by this extension, the documentation displayed comes from the TypeScript language server. You can see the same `...` in hovers.

Please file an issue against TypeScript if you feel this could be improved
