### ISSUE TITLE
Characters not easy to distinguish on some light themes

### ISSUE THREAD

**Issue by allefeld** [mattbierner/vscode-docs-view#24]
With the theme **Light (Visual Studio)**, part of the signature is hard to read.

![image](https://user-images.githubusercontent.com/1738353/106963349-5c578080-6738-11eb-8071-04554271d361.png)

Since the same problem does not occur in VS Code's own popup:

![image](https://user-images.githubusercontent.com/1738353/106963542-9f195880-6738-11eb-8ccf-8f319aeda5ec.png)

could you maybe modify the extension so it uses the same colors as those in the popup?

As a side note, I would also prefer the slightly larger font used in the popup.

A workaround is to switch to the very similar **Light+ (default light)**.

***

I checked the other light themes, and similar problems occur with **Quiet Light**

![image](https://user-images.githubusercontent.com/1738353/106963854-1b13a080-6739-11eb-9bbd-2310cf3f8731.png)

and **Solarized Light**

![image](https://user-images.githubusercontent.com/1738353/106963965-48f8e500-6739-11eb-8bfb-9d3fdd5607f6.png)

**Comment by mattbierner** [comment]
Please test out 0.0.9 which should fix this. If you still see issues, please share codes snippets that cause problems so I can investigate

**Comment by allefeld** [comment]
Yes, the problem is fixed for all three light themes. Thanks!
