### ISSUE TITLE
How to view documentation in pug file?

### ISSUE THREAD

**Issue by AntonGrekov** [mattbierner/vscode-docs-view#27]
I am sorry, question is most likelty not related to your awesome extension( i installed it just when i first saw it, good job)
But can someone please point me out to how do i enable, for example, php documentation inside <?php ... ?> code blocks in .pug template files ? Or any other, would be awesome if vscode could still provide documentation no matter what current file extension is by learing current language out of context. Thx

**Comment by mattbierner** [comment]
This extension uses IntelliSense from the other extensions you have installed. Try [checking the marketplace](https://marketplace.visualstudio.com/search?term=pug&target=VSCode&category=All%20categories&sortBy=Relevance) to see if there is a good one for Pug
