### ISSUE TITLE
Stops working suddenly

### ISSUE THREAD

**Issue by kaychess** [mattbierner/vscode-docs-view#28]
Thank you for the docs view. It helps me very much in my coding. 

Apart from that, One issue I often face is, It stops working suddenly in-between projects. 
Can you please check on this once? I know the issue I stated is very generic. It is due to the lack of VSCode extension debugging tools. Nevertheless can you please try to have a look if there are any possibilities for it to get stopped? 
Often I need to reinstall the extension to get it to work again.

<img width="992" alt="Screen Shot 2021-05-20 at 9 13 25 PM" src="https://user-images.githubusercontent.com/47786857/119067875-02aa5780-b9b1-11eb-88ea-f2acad1d7093.png">

**Comment by mattbierner** [comment]
Without more specific info about the error or steps  to reproduce this, this is not actionable. Please try to see if you can track down what seems to cause this issue so I can investigate fixing it
