### ISSUE TITLE
Version reqs

### ISSUE THREAD

**Issue by buggymcbugfix** [mattbierner/vscode-docs-view#3]
What are the version requirements for this extension? I did not find it in the documentation.
<img width="413" alt="Screenshot 2020-10-04 at 10 09 15" src="https://user-images.githubusercontent.com/17603372/95010482-00fe7000-062a-11eb-8b52-2a130ba8240d.png">

**Comment by RandomFractals** [comment]
you need vscode v1.50 since webview view api Matt is using for this extension has been released in that version and will not work in prior vscode versions.

see: https://code.visualstudio.com/updates/v1_50
