### ISSUE TITLE
Documentation display issue

### ISSUE THREAD

**Issue by mikeerickson** [mattbierner/vscode-docs-view#35]
The documentation description seems quite large

![CleanShot 2022-04-04 at 05 59 09](https://user-images.githubusercontent.com/183153/161548959-0849b52b-862b-4257-919e-dbe4d77a5acf.png)

**Comment by mattbierner** [comment]
Please provide steps to reproduce the issue

**Comment by mattbierner** [comment]
Closing as needs more info
