### ISSUE TITLE
Please publish this extension to the open-vsx.org registry (to support VSCodium)

### ISSUE THREAD

**Issue by herrherrmann** [mattbierner/vscode-docs-view#37]
I would love to use this extension with [VSCodium](https://vscodium.com/). For that to work, the extension would need to be published to the open-source registry at openvsx. A guide on how to do that can be found here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Alternatively, the extension could be added to the [publish-extensions repo](https://github.com/open-vsx/publish-extensions) as a workaround, but that would not be a good long-term solution for reasons described [here](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension=).

I know it’s a few steps to follow, but please consider this! I’d be very grateful. <3

**Comment by mattbierner** [comment]
I don't plan on testing or supporting this extension on any anything other that official VS Code builds
