### ISSUE TITLE
Support to navigate to internal links

### ISSUE THREAD

**Issue by egamma** [mattbierner/vscode-docs-view#4]
The Docs view supports to navigate to external links. However, navigating to internal links is not supported, see below

![image](https://user-images.githubusercontent.com/172399/95165258-ece27c00-07ab-11eb-88ef-3632804e7227.png)

**Comment by mattbierner** [comment]
These links are also not supported in hovers (they only work when you are viewing `vscode.d.ts`).

Support for them is tracked by TypeScript here: https://github.com/microsoft/TypeScript/issues/35524
