### ISSUE TITLE
Intermittently failing -- "Error loading webview"

### ISSUE THREAD

**Issue by jorgenpt** [mattbierner/vscode-docs-view#40]
I'm not sure what triggers it, but sometimes the view will be completely empty. It will trigger an error notify with the title "Error loading webview", and closing & re-opening the sidebar it's in will re-trigger the error. The only workaround I've found is to restart VSCode.

The full error notify reads

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

Version:
```
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

"Update Mode" is "Live".

**Comment by mattbierner** [comment]
This is a core VS Code issue, not an issue with this extension
