### ISSUE TITLE
Expose option to change doc font size

### ISSUE THREAD

**Issue by mezdelex** [mattbierner/vscode-docs-view#41]
Hi, I've using the extension quite a bit lately but I find the font size a bit small compared to the rest of the editor font size (14).

Would it be possible to expose font size configuration option? 

![image](https://user-images.githubusercontent.com/59997405/200271092-0a16ae2d-1882-41fb-9d52-cd352aa54117.png)

Thanks in advance.

**Comment by vedal** [comment]
already in #30 ?

**Comment by mezdelex** [comment]
> already in #17 and #30 ?

You're right, sorry.
