### ISSUE TITLE
case where definitions don't load

### ISSUE THREAD

**Issue by Hifilo** [mattbierner/vscode-docs-view#43]
Hello, This is a great extention, but I noticed it doesn't always work for me in Javascript. Here is one condition:

![Code_FAyMp87oq9](https://user-images.githubusercontent.com/92943726/222937077-190174d4-de19-4b15-860d-39a1d198ecc8.gif)

I'm not sure if this is an error on my end, but it works fine when methods aren't being chained. If chaining it doesn't seem to recognize what I have at the cursor.

**Comment by mattbierner** [comment]
This extension only shows IntelliSense provided by other language extensions (the same you see on hover). It does not calculate anything itself

In this case the IntelliSense comes from VS Code's built-in JS/TS extension. You just need to add a few typings to fix it
