### ISSUE TITLE
It does not provide documentation in some cases

### ISSUE THREAD

**Issue by GitHunter0** [mattbierner/vscode-docs-view#46]
Hey, first congratulations for this very useful and necessary extension, since VScode has critical issues in the regard of displaying documentation.

Consider this example:
```python
import datar.all as d
import pandas as pd
df = pd.DataFrame({'x':[1,2,4]})
d.glimpse(df)
```
When I hover on `glimpse`, I don't get the proper documentation, Docs View only shows `(function) glimpse: Any`.

It would be really great to get the full documentation, something that so far no other extension was able to provide.

Thank you.

**Comment by mjbvz** [comment]
This extension shows documentation that language extensions provide. If the documentation itself is incorrect, please file an issue against the language extension (python)
