### ISSUE TITLE
Syntax highlighting broken?

### ISSUE THREAD

**Issue by PSAGChristian** [mattbierner/vscode-docs-view#48]
Hi,

I recently noticed that syntax highlighting may be broken in general.
It used to work for JavaScript, for example, but now it doesn't.

![image](https://github.com/mattbierner/vscode-docs-view/assets/114414556/5df69d16-1fed-4c0d-b8c2-0ee723552ceb)

Docs View: v0.0.11
VSCode: v1.82.2

I really like this extension and would be happy if this could be fixed.

**Comment by florius0** [comment]
Same problem with Elixir, hope it'll be fixed

**Comment by mattbierner** [comment]
Should be fixed in 0.1.0

If not, please share steps to reproduce this including example code as text

**Comment by PSAGChristian** [comment]
Thanks a lot! It's working 👍
