### ISSUE TITLE
Not working in Python with MS Python/Pylance extensions or in C/C++ with the MS C/C++ extension

### ISSUE THREAD

**Issue by tristan957** [mattbierner/vscode-docs-view#5]
Hey Matt,

I thought your extension sounded pretty good from the VSCode release notes, so I chose to install it. I have a Python/C/C++ project at the moment that I thought it would be nice to try it out on.

From the README, it says the extension is language agnostic, but I cannot get any info to show up. On hover of various functions and modules in a python file or functions/structs in a C/C++ file, I see the documentation and function signature. Your extension is not showing any documentation when my cursor is within a module/class/function/struct that has documentation associated with it.

For reference, not that it might matter, I am using the extension in a Remote - SSH env.

VSCode version - 1.50

**Comment by RMBeristain** [comment]
I can't get it to work either. My project setup is a bit convoluted:

Source files are stored in windows, but I access them through WSL (e.g. /mnt/c/path/to/file.py )
Also tried with javascript files on that project, but doc info doesn't show for those either.

**Comment by mattbierner** [comment]
Does it work in a non-ssh environment? Can you provide specific steps to reproduce the issue?

**Comment by gjsjohnmurray** [comment]
@tristan957 are you only hovering over the symbol you are interested in? I think you need to put the text cursor into the symbol, not just hover the mouse pointer over it. Easy way is to click on it.

**Comment by tristan957** [comment]
@gjsjohnmurray sorry if I wasn't clear. I am definitely putting my cursor within the name of the function/variable/module I am trying to get documentation for.

@mattbierner steps to reproduce:

1. Open an untitled file on your local machine
2. Mark the language mode as html
3. Type in `<html></html>`
4. Notice the docs in Docs View web view

Repeating these steps in my remote ssh env does not show the docs like it does on my local machine. I was also able to repeat using remote wsl. Seems like it could maybe be an issue with webviews in remote environments? I don't know of another webview to use to confirm my hypothesis at the moment.

**Comment by yogan** [comment]
I'm pretty sure it has something to do with running in WSL.

I work a lot in WSL remotes, too, and noticed that nothing shows up in the documentation pane.
It's not dependent on the language. To be sure, I tested this with opening the VS Code's `settings.json`.
Outside of a WSL remote, the settings are showing their docs in the pane just fine. When doing the
same in a WSL remote, the pane stays empty.

Let me know if I can somehow provide more information. Is there maybe a way to get some debug
output from the extension?

**Comment by RMBeristain** [comment]
I have tried in regular Windows projects and it works perfectly, no issues so far.
But on WSL,nothing shows up for any language I've tried.

Also tried opening the same file:
- Windows: `C:\Users\me\Documents\bootstrap.js`
- WSL: `/mtn/c/Users/me/Documents/bootstrap.js`

Both files show tooltips when I hover over a function with the mouse, but when I click on the function Docs view only updates on Windows.

Please let me know if there are some logs or other details I can provide you to troubleshoot.

**Comment by mattbierner** [comment]
Please try out the new 0.0.4 release of this extension and let me know if there are any cases where it does not work

**Comment by yogan** [comment]
I've just tried and can confirm that it works (used WSL2 and a TS project, but I assume anything should work now).

Thanks so much!
