### ISSUE TITLE
Syntax highlighting not being applied

### ISSUE THREAD

**Issue by serras** [mattbierner/vscode-docs-view#6]
First of all, thanks for this extension. It has made my life a bit easier and my code navigation a bit more comfortable :)

It seems however, that something is preventing syntax highlighting to be applied to the docs. In the attached image you can see some (Haskell) code on the right, and then the docs on the left, all in black and white. I've double-checked, and the documentation is coloured in the hover view.

![Captura de pantalla 2020-10-09 a las 9 34 52](https://user-images.githubusercontent.com/309334/95556541-c0c93400-0a13-11eb-97ff-8bde2a2dfce4.png)

For the record, I have some extensions installed which work on Markdown: Github Markdown Preview, Markdown Checkboxes and Markdown Emoji. I don't know if those conflict in any way.

I am also happy to contribute a patch with some guidance. After all, it's Hacktoberfest season!

**Comment by mattbierner** [comment]
Please share steps to reproduce this issue (including example code as text)

**Comment by serras** [comment]
- Install VSCode and the [Haskell extension](https://marketplace.visualstudio.com/items?itemName=haskell.haskell)
- Create a file named `Module.hs` with the following contents:

```haskell
module Module where

f :: Int
f = 5
```
- Wait a while until the Haskell extension is set up for the first time and loads the file.
- If you hover over `Int` you see `Int :: *` with syntax highlighting, but on the `Documentation` panel this is on black.
