### ISSUE TITLE
Characters not easy to distinguish on dark themes

### ISSUE THREAD

**Issue by Gurran** [mattbierner/vscode-docs-view#7]
As you can see on the image, many of the characters are hard to distinguish on dark themes.

Horizon
![image](https://user-images.githubusercontent.com/42462633/95564036-7e592480-0a1e-11eb-9c82-d3b54c36843a.png)

Dark+
![image](https://user-images.githubusercontent.com/42462633/95564216-c4ae8380-0a1e-11eb-8b74-21dedc9b191f.png)

Abyss
![image](https://user-images.githubusercontent.com/42462633/95564351-f3c4f500-0a1e-11eb-9bc3-e1f2b5336c66.png)

**Comment by Gurran** [comment]
I don't know if it's possible but the text should be shown in the same way as the colorscheme.

**Comment by mattbierner** [comment]
Please share steps to reproduce the issue. Which color them for example?

**Comment by Gurran** [comment]
I've disabled all extensions and just enabled vscode-docs-view.

I have a simple code test:
```typescript
console.log("Testing Themes")
```

While placing the cursor on log and switching themes I look for changes in the docs window.

Some seem to work and some don't.

### Abyss ❌ 
![image](https://user-images.githubusercontent.com/42462633/96091735-3fb5e500-0eca-11eb-85c6-9c385beda7f9.png)
![image](https://user-images.githubusercontent.com/42462633/96089505-37a87600-0ec7-11eb-9937-15f2146ac643.png)

### Dark+ 💹 

![image](https://user-images.githubusercontent.com/42462633/96091849-6247fe00-0eca-11eb-9d64-9fbeb892ddd4.png)
![image](https://user-images.githubusercontent.com/42462633/96091878-683ddf00-0eca-11eb-9a60-9a17faff01db.png)

**Comment by Gurran** [comment]
Sometimes a theme will not work. If I then change themes back and fourth a bit it sometimes starts to work again. As you can see on Dark+ theme that didn't initially work but now do. 

Abyss (built-in theme) never works.

**Comment by tristan957** [comment]
This is what I see with regard to this issue.

theme: One Dark Pro
code:
```cpp
struct {
        /* mirror selected kvdb_rparams */
        u64 csched_samp_max;
        u64 csched_lo_th_pct;
        u64 csched_hi_th_pct;
        u64 csched_leaf_pct;
    } inputs;
```
![image](https://user-images.githubusercontent.com/11936772/96465470-9f73ff00-11ee-11eb-94eb-5a5a87dfc469.png)

**Comment by mattbierner** [comment]
Should be improved with 0.0.5. Let me know if there are any themes that still have issues

Keep in mind though that because the docs view has a different background color than the editor, some colors may visually look slightly different between the two (see the much darker editor background for `Kimbie Dark` for example):

<img width="1117" alt="Screen Shot 2020-10-19 at 10 20 27 PM" src="https://user-images.githubusercontent.com/212305/96544636-ca486c80-125b-11eb-8f73-b050aec667f1.png">

**Comment by tristan957** [comment]
I tried this out, and the experience is much improved. One thing that I thought was interesting was Docs View even showed git blame documentation coming from GitLens. Thanks Matt.

**Comment by Gurran** [comment]
The new version works flawlessly for me. 

Thanks for the help!
