### ISSUE TITLE
Add VS Code API docs search

### ISSUE THREAD

**Issue by RandomFractals** [mattbierner/vscode-docs-view#8]
First of all, this is really great for showing docs in a sidebar as we code.

Please consider adding Topics dropdown and vscode api search to this extension for extension devs from:

https://code.visualstudio.com/api/references/vscode-api

So we can load docs topics & search docs from vscode without switching to browser.

Same can be applied to other docs sites for other launguages and apis. This seems like a good extension to implement that idea.

Thanks!

**Comment by mattbierner** [comment]
Closing this as out of scope for this extension. A different extension could provide more of a documentation browser

**Comment by RandomFractals** [comment]
that's fine. I do like what Kite does for Py tho: https://www.kite.com/copilot/

maybe they'll add insta docs search for JS soon too.
